### ISSUE TITLE
BLEBeacon  not declared

### ISSUE THREAD

**Issue by gerisse** [chegewara/esp32-tests-library#1]
Hi Chegewara
i tried to compile the ibeacon test : i have this error : 
_ibeacon_test/main/./main.cpp:27:3: error: 'BLEBeacon' was not declared in this scope__
i don't think i made a mistake : 
i added the components/cpp_utils directory and i ran the sdk config before with "make menuconfig"
an idea ?
thanks

**Comment by chegewara** [comment]
this code has been working, but maybe try to add this include in main.cpp:
`#include <BLEBeacon.h>`

**Comment by gerisse** [comment]
yes , effectively, it works with this instruction. thanks

**Comment by gerisse** [comment]
hi,
another issue appears : eclipse says error at this line : 
"#include string"   (i deleted <> cause marrkdown editor)
(but not for "#include <string.h>)
and for : 
  BLEDevice::init("MyESP32");  ( Function 'init' could not be resolved)
  BLEServer *pServer = BLEDevice::createServer(); ( Description	Resource	Path	Location	Type
Type 'BLEServer' could not be resolved)
i guess these two late errors are result of the first
an idea of the cause ?
however, compilation and flash are ok
thanks

**Comment by chegewara** [comment]
Its because eclipse is stupid. Ive been able only one time to configure eclipse such way so i dont have any problems (ubuntu 14.10), ive been trying to do the same on my home server with ubuntu 16, ubuntu 17 and im having the same issues as you. And for some reason its BLESever, even if i have all paths setup correctly.
